# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference

# For a detailed guide to building and testing with Python, read the docs:
# https://circleci.com/docs/language-python/ for more details
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # See the Python orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@2.1.1
  codecov: codecov/codecov@5
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs

jobs:
  build-and-test:
    parameters:
      python:
        type: string
    docker:
      - image: cimg/python:<< parameters.python >>
    steps:
      - checkout
      - run:
          name: Install dependencies from pyproject.toml
          command: |
            pip install .
            pip install .[zstd]
            pip install .[test]
            pip install --force-reinstall .[dev]
            pip install codecov-cli
      - run:
          name: Run tests
          command: pytest --cov-report xml --junitxml=pytest.<< parameters.python >>.junit.xml -o junit_family=legacy
      - run:
          name: Run ruff
          command: ruff check --respect-gitignore --output-format junit --output-file ruff.<< parameters.python >>.junit.xml aesfile/ || true
      - run:
          name: Upload tests result
          command: codecovcli do-upload --report-type test_results --file pytest.<< parameters.python >>.junit.xml --file ruff.<< parameters.python >>.junit.xml

  build-and-cov:
    parameters:
      python:
        type: string
    docker:
      - image: cimg/python:<< parameters.python >>
    steps:
      - checkout
      - run:
          name: Install dependencies from pyproject.toml
          command: |
            pip install .
            pip install .[zstd]
            pip install .[test]
            pip install --force-reinstall .[dev]
            pip install codecov-cli
      - run:
          name: Run tests
          command: pytest -n auto --ignore=tests/test_benchmark.py --cov-report xml --junitxml=pytest.<< parameters.python >>.junit.xml -o junit_family=legacy
      - run:
          name: Run ruff
          command: ruff check --respect-gitignore --output-format junit --output-file ruff.<< parameters.python >>.junit.xml aesfile || true
      - codecov/upload
      - run:
          name: Upload tests result
          command: codecovcli do-upload --report-type test_results --file pytest.<< parameters.python >>.junit.xml --file ruff.<< parameters.python >>.junit.xml

  testpypi_publish:
    parameters:
      python:
        type: string
    docker:
      - image: cimg/python:<< parameters.python >>
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Install dependencies from pyproject.toml
          command: |
            pip install .
            pip install .[build]
      - run:
          name: Build package
          command: python3 -m build
      - run:
          name: Upload
          command: python3 -m twine upload --repository testpypi --verbose --user $TWINE_USERNAME --password $TWINE_PASSWORD dist/*

  pypi_publish:
    parameters:
      python:
        type: string
    docker:
      - image: cimg/python:<< pipeline.parameters.python >>
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Install dependencies from pyproject.toml
          command: |
            pip install .
            pip install .[build]
      - run:
          name: Build package
          command: python3 -m build
      - run:
          name: Upload
          command: python3 -m twine upload --verbose --user $TWINE_USERNAME --password $TWINE_PROD_PASSWORD dist/*

workflows:
  sample:
    jobs:
      - build-and-test:
          matrix:
            parameters:
                python : ['3.9', '3.10', '3.11']
      - build-and-cov:
          matrix:
            parameters:
                python : ['3.12']
#      - testpypi_publish:
#          requires:
#            - build-and-test
#          filters:
#            tags:
#              only: /^.*[ab]+.*$/
